#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# SPDX-License-Identifier: MIT
# Copyright (C) 2020-2021 Mobica Limited

"""Command line script creating sprint definition file"""

# Standard library imports
import sys
import datetime
import json

# Third party imports
import jsonschema
import tabulate

# Project imports
import cjm
import cjm.cfg
import cjm.codes
import cjm.data
import cjm.request
import cjm.run
import cjm.schema
import cjm.sprint


_PROJECT_KEY_ARG_NAME = "--project-key"


def parse_options(args, defaults):
    """Parse command line options"""
    parser = cjm.cfg.make_common_parser(defaults)

    default_length = 14
    default_project_key = defaults.get("project", {}).get("key")
    default_project_code = defaults.get("project", {}).get("code")
    default_project_sow = defaults.get("project", {}).get("sow")

    project_code_long = "--project-code"
    project_sow_long = "--project-sow"

    start_flags = parser.add_mutually_exclusive_group()
    start_flags.add_argument(
        "--next-week", action="store_true", dest="next_week_flag",
        help=(
            "The first day of the sprint is the next week's Monday. This option is the default"
            " if none of sprint start options is given"))
    start_flags.add_argument(
        "--this-week", action="store_true", dest="this_week_flag",
        help="The first day of the sprint is this week's Monday")
    start_flags.add_argument(
        "--last-week", action="store_true", dest="last_week_flag",
        help="The first day of the sprint is the last week's Monday")
    start_flags.add_argument(
        "--start", action="store", metavar="DATE", dest="start_date",
        type=lambda d: datetime.datetime.strptime(d, '%Y-%m-%d').date(),
        help="The first day of the sprint is the DATE (yyyy-mm-dd)")
    parser.add_argument(
        "--length", action="store", metavar="DAYS", dest="length", type=int,
        default=default_length,
        help="The sprint length in DAYS (default: {0:d})".format(default_length))
    parser.add_argument(
        project_code_long, action="store", metavar="CODE", dest="project_code",
        default=default_project_code,
        help=("The project CODE name to be used to form the sprint comment prefix{0:s}"
              "".format(cjm.cfg.fmt_dft(default_project_code))))
    parser.add_argument(
        project_sow_long, action="store", metavar="CODE", dest="project_sow",
        default=default_project_sow,
        help=(
            "The project sow (scope of work) CODE to be used to form the sprint comment"
            " prefix{0:s}"
            "".format(cjm.cfg.fmt_dft(default_project_sow))))

    parser.add_argument(
        _PROJECT_KEY_ARG_NAME, action="store", metavar="KEY", dest="project_key",
        default=default_project_key,
        help=(
            "Project with which the sprint will be associated{0:s}"
            "".format(cjm.cfg.fmt_dft(default_project_key))))

    parser.add_argument(
        "team_file", action="store",
        help=(
            "Path to the json team data file as generated by the {0:s} script and described by"
            " the {1:s} schema"
            "".format(cjm.SM_CREATE_TEAM_FILE, cjm.schema.make_subpath("team.json"))))

    options = parser.parse_args(args)

    if options.project_code is None:
        parser.error(
            "Project code not specified. Use the '{0:s}' option or the defaults file to specify it"
            "".format(project_code_long))

    if options.project_sow is None:
        parser.error(
            "Project sow not specified. Use the '{0:s}' option or the defaults file to specify it"
            "".format(project_sow_long))

    return options


def determine_start_date(options):
    """Determine sprint start date basing on provided CLI options"""
    if options.start_date is not None:
        return options.start_date
    else:
        today = datetime.date.today()
        week_offset = 7 if options.last_week_flag else 0 if options.this_week_flag else -7
        return today - datetime.timedelta(days=today.weekday()+week_offset)


def main(options, defaults):
    """Entry function"""
    cfg = cjm.cfg.apply_options(cjm.cfg.apply_config(cjm.cfg.init_defaults(), defaults), options)
    cfg["project"]["key"] = options.project_key

    if cfg["project"]["key"] is None:
        sys.stderr.write(
            "ERROR: The project key is not specified. Use the '{0:s}' CLI option or the defaults"
            " file to specify it".format(_PROJECT_KEY_ARG_NAME))
        return cjm.codes.CONFIGURATION_ERROR

    project_data_url = cjm.request.make_cj_url(cfg, "project", cfg["project"]["key"])
    response = cjm.request.make_cj_request(cfg, project_data_url)
    project_json = response.json()

    start_date = determine_start_date(options)
    end_date = start_date + datetime.timedelta(days=options.length-1)

    if cfg["sprint"]["id"] is not None:
        sprint_id = int(cfg["sprint"]["id"])
    else:
        sprint_id = None

    sprint = {
        "start date": start_date.isoformat(),
        "end date": end_date.isoformat(),
        "name": cjm.sprint.generate_sprint_name(cfg, project_json["name"], start_date, end_date),
        "id": sprint_id,
        "comment prefix": "{0:s}/{1:s}/{2:s}/{3:s}".format(
            cfg["project"]["comment ns"],
            options.project_sow, options.project_code,
            cjm.sprint.generate_sprint_period_name(cfg, start_date, end_date)),
        "project": {
            "key": cfg["project"]["key"],
            "name": project_json["name"]
        },
        "file": {
            "team": options.team_file,
            "capacity": None,
            "commitment": None,
            "delivery": None
        }
    }

    sprint["file"]["capacity"] = cjm.data.make_default_file_name(cfg, sprint, "capacity")
    sprint["file"]["commitment"] = cjm.data.make_default_file_name(cfg, sprint, "commitment")
    sprint["file"]["delivery"] = cjm.data.make_default_file_name(cfg, sprint, "delivery")

    sprint_schema = cjm.schema.load(cfg, "sprint.json")
    jsonschema.validate(sprint, sprint_schema)

    if options.json_output:
        print(json.dumps(sprint, indent=4, sort_keys=False))
    else:
        print(tabulate.tabulate(
            [(key, sprint[key]) for key in ["start date", "end date", "name"]] +
            [("project/{0:s}".format(key), sprint["project"][key]) for key in ["key", "name"]] +
            [("file/{0:s}".format(key), sprint["file"][key])
             for key in ["team", "capacity", "commitment", "delivery"]],
            tablefmt="orgtbl"))

    return cjm.codes.NO_ERROR


if __name__ == '__main__':
    cjm.run.run_2(main, parse_options)
