#!/usr/bin/env python3

# Standard library imports
import sys

# Third party imports
import simplejson
import tabulate

# Project imports
from odf.opendocument import OpenDocumentText
from odf.style import Style, ParagraphProperties, TableColumnProperties
from odf.table import Table, TableColumn, TableRow, TableCell
from odf.text import P

import cjm
import cjm.cfg
import cjm.issue
import cjm.request
import cjm.schema
import cjm.sprint
import cjm.team
import cjm.codes

SPRINT_ARG_NAME = "--by-sprint"
COMMENT_ARG_NAME = "--by-comment"
ODT_FILE_ARG_NAME = "--odt-file"


def parse_options(args):
    defaults = cjm.cfg.load_defaults()
    parser = cjm.cfg.make_common_parser(defaults)

    parser.add_argument(
        "sprint_file", action="store",
        help=(
            "Path to the json sprint data file as generated by the {0:s} script and described by"
            " the {1:s} schema"
            "".format(cjm.SM_CREATE_SPRINT_FILE, cjm.schema.make_subpath("sprint.json"))))

    parser.add_argument(
        "team_file", action="store",
        help=(
            "Path to the json team data file as generated by the {0:s} script and described by"
            " the {1:s} schema"
            "".format(cjm.SM_CREATE_TEAM_FILE, cjm.schema.make_subpath("team.json"))))

    parser.add_argument(
        SPRINT_ARG_NAME, action="store_true", dest="by_sprint_flag",
        help=(
            "Select issues associated with the given sprint. Can be conbined with '{0:s}' flag"
            "".format(COMMENT_ARG_NAME)))
    parser.add_argument(
        COMMENT_ARG_NAME, action="store_true", dest="by_comment_flag",
        help=(
            "Select issues with the commitment comment added. Can be conbined with '{0:s}' flag"
            "".format(SPRINT_ARG_NAME)))
    parser.add_argument(
        ODT_FILE_ARG_NAME, action="store_true", dest="odt_file_output",
        help=(
            "Output data in .odt file format."
        ))

    return parser.parse_args(args)


def main(options):
    cfg = cjm.cfg.apply_options(cjm.cfg.init_defaults(), options)

    try:
        with open(options.sprint_file) as sprint_file:
            sprint_data = cjm.sprint.load_data(cfg, sprint_file)
    except IOError as e:
        sys.stderr.write(
            "ERROR: Sprint data file ('{0:s}') I/O error\n".format(options.sprint_file))
        sys.stderr.write("    {0}\n".format(e))
        return cjm.codes.FILESYSTEM_ERROR

    cfg["sprint"]["id"] = sprint_data.get("id")
    cfg["project"]["key"] = sprint_data["project"]["key"]

    if cfg["sprint"]["id"] is None:
        sys.stderr.write(
            "ERROR: The sprint id is not specified by the sprint data file ('{0:s}')\n"
            "".format(options.sprint_file))
        return cjm.codes.CONFIGURATION_ERROR

    try:
        with open(options.team_file) as team_file:
            team_data = cjm.team.load_data(cfg, team_file)
    except IOError as e:
        sys.stderr.write(
            "ERROR: Team data file ('{0:s}') I/O error\n".format(options.team_file))
        sys.stderr.write("    {0}\n".format(e))
        return cjm.codes.FILESYSTEM_ERROR

    if cfg["jira"]["fields"]["story points"] is None:
        result_code, field_id = cjm.issue.detect_story_point_field_id(cfg)
        if result_code:
            return result_code
        cfg["jira"]["fields"]["story points"] = field_id

    valid_account_id_list = [r["account id"] for r in team_data["people"]]

    # Retrieve issues assigned to the sprint:

    result_code, issues_all = cjm.sprint.request_issues_by_sprint(cfg)

    if result_code:
        return result_code

    issues_team = [i for i in issues_all if i["assignee id"] in valid_account_id_list]
    for issue in issues_team:
        issue["by sprint"] = True
        issue["by comment"] = False

    issue_lut = dict((i["id"], i) for i in issues_team)

    # Retrieve issues with the commitment comment added:

    result_code, issues_all = cjm.sprint.request_issues_by_comment(
        cfg, "{0:s}/Committed".format(sprint_data["comment prefix"]))

    if result_code:
        return result_code

    issues_team = [i for i in issues_all if i["assignee id"] in valid_account_id_list]

    for issue in issues_team:
        issue_id = issue["id"]
        if issue_id in issue_lut:
            issue_lut[issue_id]["by comment"] = True
        else:
            issue_lut[issue_id] = issue
            issue_lut[issue_id]["by sprint"] = False
            issue_lut[issue_id]["by comment"] = True

    issue_lut.update(dict((i["id"], i) for i in issues_team if i["id"] not in issue_lut))

    issues = [issue_lut[k] for k in sorted(issue_lut.keys())]

    if options.json_output:
        print(simplejson.dumps({"issues": issues}, indent=4, sort_keys=False))
    else:
        person_lut = dict((p["account id"], p) for p in team_data["people"])
        print(tabulate.tabulate(
            [(i["id"], i["key"], i["summary"],
              "{0:s}, {1:s}".format(
                  person_lut[i["assignee id"]]["last name"],
                  person_lut[i["assignee id"]]["first name"]),
              i["story points"],
              "Sprint" if i["by sprint"] else "",
              "Comment" if i["by comment"] else "")
             for i in issues],
            headers=["Id", "Key", "Summary", "Assignee", "Story Points", "Sprint", "Comment"],
            tablefmt="orgtbl"))

    if options.odt_file_output:
        textdoc = OpenDocumentText()
        # Create a style for the table content. One we can modify
        # later in the word processor.
        tablecontents = Style(name="Table Contents", family="paragraph")
        tablecontents.addElement(ParagraphProperties(numberlines="false", linenumber="0"))
        textdoc.styles.addElement(tablecontents)

        # Create automatic styles for the column widths.
        # We want two different widths, one in inches, the other one in metric.
        # ODF Standard section 15.9.1
        w1 = Style(name="w1", family="table-column")
        w1.addElement(TableColumnProperties(columnwidth="2cm"))
        textdoc.automaticstyles.addElement(w1)

        w2 = Style(name="w2", family="table-column")
        w2.addElement(TableColumnProperties(columnwidth="13cm"))
        textdoc.automaticstyles.addElement(w2)

        w3 = Style(name="w3", family="table-column")
        w3.addElement(TableColumnProperties(columnwidth="2cm"))
        textdoc.automaticstyles.addElement(w3)

        # Start the table, and describe the columns
        table = Table()
        table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=w1))
        table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=w2))
        table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=w3))

        table_header = TableRow()
        table.addElement(table_header)

        tc1_top = TableCell()
        table_header.addElement(tc1_top)
        p = P(stylename=tablecontents, text="Task ID")
        tc1_top.addElement(p)

        tc2_top = TableCell()
        table_header.addElement(tc2_top)
        p = P(stylename=tablecontents, text="Task Title")
        tc2_top.addElement(p)

        tc3_top = TableCell()
        table_header.addElement(tc3_top)
        p = P(stylename=tablecontents, text="Story Points")
        tc3_top.addElement(p)

        rows_containing_data = 1

        for issue in issues:
            tr = TableRow()
            table.addElement(tr)

            tc1 = TableCell()
            tr.addElement(tc1)
            p = P(stylename=tablecontents, text=issue["key"])
            tc1.addElement(p)

            tc2 = TableCell()
            tr.addElement(tc2)
            p = P(stylename=tablecontents, text=issue["summary"])
            tc2.addElement(p)

            tc3 = TableCell()
            tr.addElement(tc3)
            p = P(stylename=tablecontents, text=issue["story points"])
            tc3.addElement(p)

            rows_containing_data += 1

        table_footer = TableRow()
        table.addElement(table_footer)

        tc1_bottom = TableCell()
        table_footer.addElement(tc1_bottom)
        p = P(stylename=tablecontents, text="")
        tc1_bottom.addElement(p)

        tc2_bottom = TableCell()
        table_footer.addElement(tc2_bottom)
        p = P(stylename=tablecontents, text="Total:")
        tc2_bottom.addElement(p)

        tc3_bottom = TableCell(stylename=tablecontents,
                               formula="SUM(<C2:C" + str(rows_containing_data) + ">)", valuetype="float")
        table_footer.addElement(tc3_bottom)

        textdoc.text.addElement(table)
        textdoc.save("./data/sample_commitment_data.odt")

    return cjm.codes.NO_ERROR


if __name__ == '__main__':
    sys.stderr.write("TODO: MOVE ODT FILE CREATION TO FUNCTION\n")
    sys.exit(main(parse_options(sys.argv[1:])))
