#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Standard library imports
import os
import sys
import datetime as dt
import json

# Third party imports
import jsonschema
import numpy as np
import holidays

from odf import dc
from odf.draw import Frame, Image
from odf.opendocument import OpenDocumentText
from odf.style import Style, ParagraphProperties, TableColumnProperties, TextProperties, GraphicProperties
from odf.table import Table, TableColumn, TableRow, TableCell
from odf.text import P, H, A

# Project imports
import cjm
import cjm.cfg
import cjm.request
import cjm.codes
import cjm.schema
import cjm.sprint

DEFAULTS_FILE_NAME = "./data/sample_commitment_data.json"


def parse_options(args):
    defaults = cjm.cfg.load_defaults()
    parser = cjm.cfg.make_common_parser(defaults)

    parser.add_argument(
        "sprint_file", action="store",
        help=(
            "Path to the json sprint data file as generated by the {0:s} script and described by"
            " the {1:s} schema"
            "".format(cjm.SM_CREATE_SPRINT_FILE, cjm.schema.make_subpath("sprint.json"))))

    parser.add_argument(
        "team_file", action="store",
        help=(
            "Path to the json team data file as generated by the {0:s} script and described by"
            " the {1:s} schema"
            "".format(cjm.SM_CREATE_TEAM_FILE, cjm.schema.make_subpath("team.json"))))

    return parser.parse_args(args)


def calculate_workdays(start_date, end_date):
    start_year = int(start_date.split("-")[0])
    end_year = int(end_date.split("-")[0])

    # NOTE: https://community.developer.atlassian.com/t/rest-api-getting-non-working-days/9851
    # "(...) there is no direct way to fetch working and non-working days for given board."

    pl_holidays = []
    for date, _ in holidays.PL(years=[start_year, end_year]).items():
        pl_holidays.append(np.datetime64(date))

    workdays = np.busday_count(np.datetime64(start_date), np.datetime64(end_date), holidays=pl_holidays)
    return workdays


def logo(textdoc):
    style = add_style(textdoc, "style")

    logo_frame = Frame(width="2.7cm", height="2.7cm", x="0cm", y="0cm", anchortype="as-char", stylename=style)
    href = textdoc.addPicture('./data/logo.jpg')
    logo_frame.addElement(Image(href=href))
    textdoc.text.addElement(logo_frame)


def data_table(textdoc, sprint_data):
    title_style = add_style(textdoc, "title_style")
    title_cell_style = add_style(textdoc, "title_cell_style")
    tab1_w1 = add_style(textdoc, "tab1_w1")
    tab1_w2 = add_style(textdoc, "tab1_w2")
    desc_cell_style = add_style(textdoc, "desc_cell_style")

    project_title, project_workweek = sprint_data["name"].split(" ")
    title = "Mobica " + project_title + " sprint commitment (" + project_workweek + ")"

    h = H(outlinelevel=1, stylename=title_style, text=title)
    textdoc.meta.addElement(dc.Title(text=title))
    textdoc.text.addElement(h)

    textdoc.text.addElement(P())

    table = Table()
    table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=tab1_w1))
    table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=tab1_w2))

    tr = TableRow()
    table.addElement(tr)

    tc1 = TableCell()
    tr.addElement(tc1)
    p = P(stylename=title_cell_style, text="Client")
    tc1.addElement(p)

    client = "INTEL"

    tc2 = TableCell()
    tr.addElement(tc2)
    p = P(stylename=desc_cell_style, text=client)
    tc2.addElement(p)

    tr = TableRow()
    table.addElement(tr)

    tc1 = TableCell()
    tr.addElement(tc1)
    p = P(stylename=title_cell_style, text="Project")
    tc1.addElement(p)

    tc2 = TableCell()
    tr.addElement(tc2)
    p = P(stylename=desc_cell_style, text=project_title)
    tc2.addElement(p)

    tr = TableRow()
    table.addElement(tr)

    tc1 = TableCell()
    tr.addElement(tc1)
    p = P(stylename=title_cell_style, text="Sprint Weeks")
    tc1.addElement(p)

    tc2 = TableCell()
    tr.addElement(tc2)
    p = P(stylename=desc_cell_style, text=project_workweek)
    tc2.addElement(p)

    tr = TableRow()
    table.addElement(tr)

    tc1 = TableCell()
    tr.addElement(tc1)
    p = P(stylename=title_cell_style, text="Sprint Duration")
    tc1.addElement(p)

    tc2 = TableCell()
    tr.addElement(tc2)
    p = P(stylename=desc_cell_style, text=sprint_data["start date"] + " to " + sprint_data["end date"])
    tc2.addElement(p)

    tr = TableRow()
    table.addElement(tr)

    tc1 = TableCell()
    tr.addElement(tc1)
    p = P(stylename=title_cell_style, text="Sprint Workdays")
    tc1.addElement(p)

    tc2 = TableCell()
    tr.addElement(tc2)
    p = P(stylename=desc_cell_style, text=calculate_workdays(sprint_data["start date"], sprint_data["end date"]))
    tc2.addElement(p)

    tr = TableRow()
    table.addElement(tr)

    tc1 = TableCell()
    tr.addElement(tc1)
    p = P(stylename=title_cell_style, text="Report Author")
    tc1.addElement(p)

    tc2 = TableCell()
    tr.addElement(tc2)
    p = P(stylename=desc_cell_style, text=" ")
    tc2.addElement(p)

    tr = TableRow()
    table.addElement(tr)

    tc1 = TableCell()
    tr.addElement(tc1)
    p = P(stylename=title_cell_style, text="Report Date")
    tc1.addElement(p)

    tc2 = TableCell()
    tr.addElement(tc2)
    p = P(stylename=desc_cell_style, text=dt.datetime.today().strftime('%d-%m-%Y'))
    tc2.addElement(p)

    textdoc.text.addElement(table)


def summary(textdoc):
    title2_style = add_style(textdoc, "title2_style")
    default_bold_style = add_style(textdoc, "default_bold_style")
    default_style = add_style(textdoc, "default_style")

    h2 = H(outlinelevel=1, stylename=title2_style, text="Summary")
    textdoc.text.addElement(h2)
    textdoc.text.addElement(P())

    story_points_committed = str(999999999999999)
    p = P(stylename=default_bold_style,
          text="     - The total number of committed story points is " + story_points_committed + ".")
    textdoc.text.addElement(p)

    sprint_capacity = str(999999999999999999999999999999999999)
    p = P(stylename=default_style, text="     - The sprint capacity is " + sprint_capacity + " story points.")
    textdoc.text.addElement(p)


def committed_tasks_list(cfg, textdoc, commitment_json):
    title2_style = add_style(textdoc, "title2_style")
    title_cell_style = add_style(textdoc, "title_cell_style")
    desc_cell_style = add_style(textdoc, "desc_cell_style")
    tab2_w1 = add_style(textdoc, "tab2_w1")
    tab2_w2 = add_style(textdoc, "tab2_w2")
    tab2_w3 = add_style(textdoc, "tab2_w3")

    h3 = H(outlinelevel=1, stylename=title2_style, text="Committed Tasks List")
    textdoc.text.addElement(h3)
    textdoc.text.addElement(P())

    table = Table()
    table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=tab2_w1))
    table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=tab2_w2))
    table.addElement(TableColumn(numbercolumnsrepeated=1, stylename=tab2_w3))

    table_header = TableRow()
    table.addElement(table_header)

    tc1_top = TableCell()
    table_header.addElement(tc1_top)
    p = P(stylename=title_cell_style, text="Task ID")
    tc1_top.addElement(p)

    tc2_top = TableCell()
    table_header.addElement(tc2_top)
    p = P(stylename=title_cell_style, text="Task Title")
    tc2_top.addElement(p)

    tc3_top = TableCell()
    table_header.addElement(tc3_top)
    p = P(stylename=title_cell_style, text="Story Points")
    tc3_top.addElement(p)

    rows_containing_data = 1

    for issue in commitment_json["issues"]:
        tr = TableRow()
        table.addElement(tr)

        commitment_issue_url = cjm.request.make_issue_url(
            cfg, "browse/{0:s}".format(issue["key"]))

        tc1 = TableCell()
        tr.addElement(tc1)
        p = P()
        a = A(stylename=desc_cell_style, href=commitment_issue_url, text=issue["key"])
        p.addElement(a)
        tc1.addElement(p)

        tc2 = TableCell()
        tr.addElement(tc2)
        p = P(stylename=desc_cell_style, text=issue["summary"])
        tc2.addElement(p)

        tc3 = TableCell()
        tr.addElement(tc3)
        p = P(stylename=desc_cell_style, text=issue["story points"])
        tc3.addElement(p)

        rows_containing_data += 1

    table_footer = TableRow()
    table.addElement(table_footer)

    tc1_bottom = TableCell()
    table_footer.addElement(tc1_bottom)
    p = P(stylename=title_cell_style, text="")
    tc1_bottom.addElement(p)

    tc2_bottom = TableCell()
    table_footer.addElement(tc2_bottom)
    p = P(stylename=title_cell_style, text="Total:")
    tc2_bottom.addElement(p)

    tc3_bottom = TableCell(stylename=title_cell_style,
                           formula="SUM(<C2:C" + str(rows_containing_data) + ">)", valuetype="float")
    table_footer.addElement(tc3_bottom)

    textdoc.text.addElement(table)


def add_style(textdoc, name):
    # STYLE
    if name == "style":
        style = Style(name='s1', parentstylename="Graphics", family="graphic")
        style.addElement(GraphicProperties(verticalpos="from-top", horizontalpos="from-left"))
        textdoc.automaticstyles.addElement(style)
        return style

    # TABLE 1 COLUMNS STYLE
    if name == "tab1_w1":
        tab1_w1 = Style(name="w1", family="table-column")
        tab1_w1.addElement(TableColumnProperties(columnwidth="4cm"))
        textdoc.automaticstyles.addElement(tab1_w1)
        return tab1_w1

    if name == "tab1_w2":
        tab1_w2 = Style(name="w2", family="table-column")
        tab1_w2.addElement(TableColumnProperties(columnwidth="13cm"))
        textdoc.automaticstyles.addElement(tab1_w2)
        return tab1_w2

    # TABLE 2 COLUMNS STYLE
    if name == "tab2_w1":
        tab2_w1 = Style(name="w1", family="table-column")
        tab2_w1.addElement(TableColumnProperties(columnwidth="2cm"))
        textdoc.automaticstyles.addElement(tab2_w1)
        return tab2_w1

    if name == "tab2_w2":
        tab2_w2 = Style(name="w2", family="table-column")
        tab2_w2.addElement(TableColumnProperties(columnwidth="12cm"))
        textdoc.automaticstyles.addElement(tab2_w2)
        return tab2_w2

    if name == "tab2_w3":
        tab2_w3 = Style(name="w3", family="table-column")
        tab2_w3.addElement(TableColumnProperties(columnwidth="3cm"))
        textdoc.automaticstyles.addElement(tab2_w3)
        return tab2_w3

    # TITLE STYLE
    if name == "title_style":
        title_style = Style(name="Mobica Heading 1", family="paragraph")
        title_style.addElement(TextProperties(attributes={'fontfamily': 'Verdana', 'fontsize': "14pt",
                                                          'fontweight': "bold"}))
        textdoc.styles.addElement(title_style)
        return title_style

    # TITLE CELL STYLE
    if name == "title_cell_style":
        title_cell_style = Style(name="Mobica Table Header Left", family="paragraph")
        title_cell_style.addElement(ParagraphProperties(padding="0.04in"))
        title_cell_style.addElement(TextProperties(attributes={'fontfamily': 'Verdana', 'fontsize': "10pt",
                                                               'fontweight': "bold"}))
        title_cell_style.addElement(GraphicProperties(fill="solid", fillcolor="#99ccff"))
        textdoc.styles.addElement(title_cell_style)
        return title_cell_style

    # DESCRIPTION CELL STYLE
    if name == "desc_cell_style":
        desc_cell_style = Style(name="Mobica Table Cell", family="paragraph")
        desc_cell_style.addElement(ParagraphProperties(padding="0.04in"))
        desc_cell_style.addElement(TextProperties(attributes={'fontfamily': 'Verdana', 'fontsize': "10pt",
                                                              'fontweight': "normal"}))
        textdoc.styles.addElement(desc_cell_style)
        return desc_cell_style

    # TITLE CELL 2 STYLE
    if name == "title2_style":
        title2_style = Style(name="Mobica Heading 2", family="paragraph")
        title2_style.addElement(
            TextProperties(attributes={'fontfamily': 'Verdana', 'fontsize': "12pt", 'fontweight': "bold"}))
        textdoc.styles.addElement(title2_style)
        return title2_style

    # DEFAULT STYLE
    if name == "default_style":
        default_style = Style(name="Default Mobica Style", family="paragraph")
        default_style.addElement(
            TextProperties(attributes={'fontfamily': 'Verdana', 'fontsize': "10pt", 'fontweight': "normal"}))
        textdoc.styles.addElement(default_style)
        return default_style

    # DEFAULT STYLE BOLD
    if name == "default_bold_style":
        default_bold_style = Style(name="Default Mobica Style Bold", family="paragraph")
        default_bold_style.addElement(
            TextProperties(attributes={'fontfamily': 'Verdana', 'fontsize': "10pt", 'fontweight': "bold"}))
        textdoc.styles.addElement(default_bold_style)
        return default_bold_style


def generate(cfg, commitment_json, sprint_data):
    textdoc = OpenDocumentText()

    logo(textdoc)

    for lines in range(4):
        textdoc.text.addElement(P())

    data_table(textdoc, sprint_data)

    for lines in range(1):
        textdoc.text.addElement(P())

    summary(textdoc)

    for lines in range(2):
        textdoc.text.addElement(P())

    committed_tasks_list(cfg, textdoc, commitment_json)

    textdoc.save("./data/sample_commitment_data.odt")


def load_defaults(file_name=DEFAULTS_FILE_NAME):
    if os.path.exists(file_name):
        try:
            with open(file_name) as defaults_file:
                defaults = json.load(defaults_file)
        except IOError as e:
            sys.stderr.write(
                "WARNING: Defaults file ('{0:s}') I/O error\n".format(file_name))
            sys.stderr.write("    {0:s}\n".format(e))
            defaults = {}
    else:
        defaults = {}

    return defaults


def main(options):
    cfg = cjm.cfg.apply_options(cjm.cfg.init_defaults(), options)

    commitment_json = load_defaults()

    commitment_schema = cjm.schema.load(cfg, "commitment.json")
    jsonschema.validate(commitment_json, commitment_schema)

    try:
        with open(options.sprint_file) as sprint_file:
            sprint_data = cjm.sprint.load_data(cfg, sprint_file)
    except IOError as e:
        sys.stderr.write(
            "ERROR: Sprint data file ('{0:s}') I/O error\n".format(options.sprint_file))
        sys.stderr.write("    {0}\n".format(e))
        return cjm.codes.FILESYSTEM_ERROR

    generate(cfg, commitment_json, sprint_data)

    return cjm.codes.NO_ERROR


if __name__ == "__main__":
    sys.stderr.write("TODO: CHANGE DEFAULT_FILE_NAME VARIABLE\n")
    sys.stderr.write("TODO: STYLE MANIPULATION\n")
    sys.stderr.write("TODO: ADD REPORTER - textdoc.meta.addElement(dc.Creator(text=))\n")
    sys.stderr.write("TODO: THINK WHAT TO DO WITH CLIENT FIELD\n")
    sys.exit(main(parse_options(sys.argv[1:])))
